### ISSUE TITLE
A question about Edge-Node Consistency.

### ISSUE THREAD

**Issue by Ytz7** [mingkai-zheng/SimMatchV2#1]
What does the “Edge-Node Consistency” have a role? I didn't see it in the overall objective of SimMatchV2. Or  I guess that the loss $L_{ne}$ contain two parts,  "Node-Edge Consistency" and "Edge-Node Consistency".

**Comment by mingkai-zheng** [comment]
The “Edge-Node Consistency”  is merged into Eq. 3. We use the propagated Y_{infinity}[0] to replace the p^{w}_{b} in Eq. 3
