### ISSUE TITLE
Question about reported result

### ISSUE THREAD

**Issue by hzhz2020** [mingkai-zheng/SimMatchV2#2]
Dear Author

Thanks for your innovative work! I just want to confirm did you report the best ema result during training or the last epoch ema result? 

I notice a similar github issue on your SimMatch paper. So just want to double check
https://github.com/mingkai-zheng/SimMatch/issues/7

**Comment by mingkai-zheng** [comment]
Yes, we report the best ema result, which is the setting adopted by the USB benchmark.
