### ISSUE TITLE
Reported results in Table1

### ISSUE THREAD

**Issue by hzhz2020** [mingkai-zheng/SimMatchV2#3]
Dear Author

In your Table1 in SimMatchV2, you said that the results of the baselines are "directly copied from the USB". However, i am confused that I couldn't find these results in the USB paper https://arxiv.org/abs/2208.07204 .Can you help me understand how did you obtain the baseline performances?

Thank you!

**Comment by mingkai-zheng** [comment]
See the Table 5 in the first version of this paper [https://arxiv.org/pdf/2208.07204v1.pdf](https://arxiv.org/pdf/2208.07204v1.pdf)

**Comment by hzhz2020** [comment]
thank you!
